## 練習時間
資料的操作有很多，接下來的馬拉松中我們會介紹常被使用到的操作，參加者不妨先自行想像一下，第一次看到資料，我們一般會想知道什麼訊息？

#### Ex: 如何知道資料的 row 數以及 column 數、有什麼欄位、多少欄位、如何截取部分的資料等等

有了對資料的好奇之後，我們又怎麼通過程式碼來達成我們的目的呢？

#### 可參考該[基礎教材](https://bookdata.readthedocs.io/en/latest/base/01_pandas.html#DataFrame-%E5%85%A5%E9%97%A8)或自行 google

# [作業目標]
- 熟悉更多的 Python 資料操作

# [作業重點]
- 列出資料的大小 (In[4], Hint : shape)
- 列出所有欄位 (In[5], 有多種寫法)
- 擷取部分資料 (In[6], Hint : loc 或 iloc)

In [1]:
import os
import numpy as np
import pandas as pd

In [2]:
# 設定 data_path
dir_data = './data/'

In [3]:
f_app = os.path.join(dir_data, 'application_train.csv')
print('Path of read in data: %s' % (f_app))
app_train = pd.read_csv(f_app)

Path of read in data: ./data/application_train.csv

### 如果沒有想法，可以先嘗試找出剛剛例子中提到的問題的答案
#### 資料的 row 數以及 column 數

In [11]:
print('資料的row數:', app_train.shape[0])

print('資料的column數:', app_train.shape[1])

資料的row數: 307511
資料的column數: 122

#### 列出所有欄位

In [15]:
for i in range(len(app_train.columns)):
    print('Column ',i + 1,': ', app_train.columns[i])

Column  1 :  SK_ID_CURR
Column  2 :  TARGET
Column  3 :  NAME_CONTRACT_TYPE
Column  4 :  CODE_GENDER
Column  5 :  FLAG_OWN_CAR
Column  6 :  FLAG_OWN_REALTY
Column  7 :  CNT_CHILDREN
Column  8 :  AMT_INCOME_TOTAL
Column  9 :  AMT_CREDIT
Column  10 :  AMT_ANNUITY
Column  11 :  AMT_GOODS_PRICE
Column  12 :  NAME_TYPE_SUITE
Column  13 :  NAME_INCOME_TYPE
Column  14 :  NAME_EDUCATION_TYPE
Column  15 :  NAME_FAMILY_STATUS
Column  16 :  NAME_HOUSING_TYPE
Column  17 :  REGION_POPULATION_RELATIVE
Column  18 :  DAYS_BIRTH
Column  19 :  DAYS_EMPLOYED
Column  20 :  DAYS_REGISTRATION
Column  21 :  DAYS_ID_PUBLISH
Column  22 :  OWN_CAR_AGE
Column  23 :  FLAG_MOBIL
Column  24 :  FLAG_EMP_PHONE
Column  25 :  FLAG_WORK_PHONE
Column  26 :  FLAG_CONT_MOBILE
Column  27 :  FLAG_PHONE
Column  28 :  FLAG_EMAIL
Column  29 :  OCCUPATION_TYPE
Column  30 :  CNT_FAM_MEMBERS
Column  31 :  REGION_RATING_CLIENT
Column  32 :  REGION_RATING_CLIENT_W_CITY
Column  33 :  WEEKDAY_APPR_PROCESS_START
Column  34 :  HOUR_APPR_PROCESS_START
Column  35 :  REG_REGION_NOT_LIVE_REGION
Column  36 :  REG_REGION_NOT_WORK_REGION
Column  37 :  LIVE_REGION_NOT_WORK_REGION
Column  38 :  REG_CITY_NOT_LIVE_CITY
Column  39 :  REG_CITY_NOT_WORK_CITY
Column  40 :  LIVE_CITY_NOT_WORK_CITY
Column  41 :  ORGANIZATION_TYPE
Column  42 :  EXT_SOURCE_1
Column  43 :  EXT_SOURCE_2
Column  44 :  EXT_SOURCE_3
Column  45 :  APARTMENTS_AVG
Column  46 :  BASEMENTAREA_AVG
Column  47 :  YEARS_BEGINEXPLUATATION_AVG
Column  48 :  YEARS_BUILD_AVG
Column  49 :  COMMONAREA_AVG
Column  50 :  ELEVATORS_AVG
Column  51 :  ENTRANCES_AVG
Column  52 :  FLOORSMAX_AVG
Column  53 :  FLOORSMIN_AVG
Column  54 :  LANDAREA_AVG
Column  55 :  LIVINGAPARTMENTS_AVG
Column  56 :  LIVINGAREA_AVG
Column  57 :  NONLIVINGAPARTMENTS_AVG
Column  58 :  NONLIVINGAREA_AVG
Column  59 :  APARTMENTS_MODE
Column  60 :  BASEMENTAREA_MODE
Column  61 :  YEARS_BEGINEXPLUATATION_MODE
Column  62 :  YEARS_BUILD_MODE
Column  63 :  COMMONAREA_MODE
Column  64 :  ELEVATORS_MODE
Column  65 :  ENTRANCES_MODE
Column  66 :  FLOORSMAX_MODE
Column  67 :  FLOORSMIN_MODE
Column  68 :  LANDAREA_MODE
Column  69 :  LIVINGAPARTMENTS_MODE
Column  70 :  LIVINGAREA_MODE
Column  71 :  NONLIVINGAPARTMENTS_MODE
Column  72 :  NONLIVINGAREA_MODE
Column  73 :  APARTMENTS_MEDI
Column  74 :  BASEMENTAREA_MEDI
Column  75 :  YEARS_BEGINEXPLUATATION_MEDI
Column  76 :  YEARS_BUILD_MEDI
Column  77 :  COMMONAREA_MEDI
Column  78 :  ELEVATORS_MEDI
Column  79 :  ENTRANCES_MEDI
Column  80 :  FLOORSMAX_MEDI
Column  81 :  FLOORSMIN_MEDI
Column  82 :  LANDAREA_MEDI
Column  83 :  LIVINGAPARTMENTS_MEDI
Column  84 :  LIVINGAREA_MEDI
Column  85 :  NONLIVINGAPARTMENTS_MEDI
Column  86 :  NONLIVINGAREA_MEDI
Column  87 :  FONDKAPREMONT_MODE
Column  88 :  HOUSETYPE_MODE
Column  89 :  TOTALAREA_MODE
Column  90 :  WALLSMATERIAL_MODE
Column  91 :  EMERGENCYSTATE_MODE
Column  92 :  OBS_30_CNT_SOCIAL_CIRCLE
Column  93 :  DEF_30_CNT_SOCIAL_CIRCLE
Column  94 :  OBS_60_CNT_SOCIAL_CIRCLE
Column  95 :  DEF_60_CNT_SOCIAL_CIRCLE
Column  96 :  DAYS_LAST_PHONE_CHANGE
Column  97 :  FLAG_DOCUMENT_2
Column  98 :  FLAG_DOCUMENT_3
Column  99 :  FLAG_DOCUMENT_4
Column  100 :  FLAG_DOCUMENT_5
Column  101 :  FLAG_DOCUMENT_6
Column  102 :  FLAG_DOCUMENT_7
Column  103 :  FLAG_DOCUMENT_8
Column  104 :  FLAG_DOCUMENT_9
Column  105 :  FLAG_DOCUMENT_10
Column  106 :  FLAG_DOCUMENT_11
Column  107 :  FLAG_DOCUMENT_12
Column  108 :  FLAG_DOCUMENT_13
Column  109 :  FLAG_DOCUMENT_14
Column  110 :  FLAG_DOCUMENT_15
Column  111 :  FLAG_DOCUMENT_16
Column  112 :  FLAG_DOCUMENT_17
Column  113 :  FLAG_DOCUMENT_18
Column  114 :  FLAG_DOCUMENT_19
Column  115 :  FLAG_DOCUMENT_20
Column  116 :  FLAG_DOCUMENT_21
Column  117 :  AMT_REQ_CREDIT_BUREAU_HOUR
Column  118 :  AMT_REQ_CREDIT_BUREAU_DAY
Column  119 :  AMT_REQ_CREDIT_BUREAU_WEEK
Column  120 :  AMT_REQ_CREDIT_BUREAU_MON
Column  121 :  AMT_REQ_CREDIT_BUREAU_QRT
Column  122 :  AMT_REQ_CREDIT_BUREAU_YEAR

#### 截取部分資料

In [16]:
#從第50筆開始截取50筆資料
app_train.iloc[50:100]

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,...,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_20,FLAG_DOCUMENT_21,AMT_REQ_CREDIT_BUREAU_HOUR,AMT_REQ_CREDIT_BUREAU_DAY,AMT_REQ_CREDIT_BUREAU_WEEK,AMT_REQ_CREDIT_BUREAU_MON,AMT_REQ_CREDIT_BUREAU_QRT,AMT_REQ_CREDIT_BUREAU_YEAR
50,100058,0,Revolving loans,F,N,Y,0,54000.0,135000.0,6750.0,...,1,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
51,100059,0,Cash loans,M,Y,Y,1,540000.0,675000.0,34596.0,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,3.0
52,100060,0,Cash loans,M,Y,N,0,76500.0,454500.0,14661.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
53,100061,0,Cash loans,F,N,Y,2,225000.0,314055.0,16164.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
54,100062,0,Cash loans,M,Y,N,0,81000.0,675000.0,32472.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
55,100063,0,Cash loans,F,N,Y,0,180000.0,837427.5,45558.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,4.0
56,100064,0,Cash loans,F,N,N,0,67500.0,298728.0,15381.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
57,100068,0,Revolving loans,M,N,Y,0,81000.0,247500.0,12375.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
58,100069,0,Cash loans,M,Y,Y,1,360000.0,640458.0,27265.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,3.0
59,100070,0,Cash loans,M,Y,Y,0,540000.0,1227901.5,46899.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
60,100071,0,Cash loans,F,N,Y,0,180000.0,1663987.5,86989.5,...,0,0,0,0,0.0,0.0,0.0,2.0,0.0,1.0
61,100072,0,Cash loans,M,N,N,0,180000.0,1080000.0,44118.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,4.0
62,100073,0,Cash loans,M,Y,Y,0,324000.0,1130760.0,40189.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,1.0
63,100075,0,Cash loans,F,N,N,0,112500.0,95940.0,10462.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
64,100076,0,Cash loans,M,Y,N,0,180000.0,315000.0,9679.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
65,100077,0,Cash loans,M,N,Y,0,180000.0,1256400.0,40657.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,8.0
66,100078,0,Cash loans,F,Y,Y,0,180000.0,1035000.0,43983.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
67,100079,0,Revolving loans,M,N,Y,0,225000.0,270000.0,13500.0,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,0.0
68,100080,0,Revolving loans,F,N,N,1,157500.0,450000.0,22500.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,5.0
69,100081,0,Cash loans,M,Y,N,0,180000.0,450000.0,21109.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
70,100082,0,Cash loans,M,N,N,2,180000.0,450000.0,21109.5,...,0,0,0,0,0.0,0.0,0.0,1.0,0.0,2.0
71,100083,0,Cash loans,M,Y,Y,0,103500.0,573628.5,24435.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
72,100084,0,Cash loans,M,N,Y,2,225000.0,495351.0,26140.5,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,0.0
73,100085,0,Cash loans,M,N,Y,1,157500.0,755190.0,28894.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
74,100086,0,Cash loans,F,N,Y,1,135000.0,675000.0,21775.5,...,0,0,0,0,0.0,0.0,0.0,1.0,4.0,2.0
75,100087,0,Cash loans,F,N,Y,1,202500.0,1288350.0,37800.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
76,100088,0,Revolving loans,F,N,N,0,112500.0,135000.0,6750.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
77,100089,0,Cash loans,M,N,Y,0,135000.0,337761.0,15781.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
78,100093,0,Cash loans,F,N,Y,1,94500.0,585000.0,28273.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
79,100094,0,Cash loans,F,N,Y,0,108000.0,113760.0,5301.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80,100095,0,Revolving loans,F,N,Y,2,67500.0,135000.0,6750.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
81,100096,1,Cash loans,F,N,Y,0,81000.0,252000.0,14593.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
82,100097,0,Cash loans,M,Y,Y,0,157500.0,760225.5,30280.5,...,0,0,0,0,0.0,0.0,1.0,0.0,0.0,0.0
83,100098,0,Revolving loans,M,Y,N,0,225000.0,270000.0,13500.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
84,100099,0,Cash loans,F,N,Y,0,360000.0,733315.5,41076.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,3.0
85,100100,0,Cash loans,M,Y,Y,2,202500.0,796396.5,38443.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
86,100101,0,Cash loans,F,Y,Y,0,202500.0,343377.0,22072.5,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN
87,100102,0,Cash loans,F,N,N,1,126000.0,327024.0,10264.5,...,0,0,0,0,0.0,0.0,0.0,6.0,0.0,0.0
88,100103,0,Cash loans,F,N,Y,0,72000.0,450000.0,16965.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
89,100104,0,Cash loans,F,N,Y,0,90000.0,547344.0,30690.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,1.0
90,100105,0,Cash loans,F,N,Y,0,193500.0,225000.0,23755.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,4.0
91,100108,0,Cash loans,F,N,Y,3,171000.0,545040.0,31288.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
92,100110,0,Cash loans,M,Y,Y,3,135000.0,373140.0,25065.0,...,0,0,0,0,0.0,0.0,0.0,0.0,1.0,2.0
93,100111,0,Cash loans,F,Y,N,1,112500.0,862560.0,27954.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
94,100112,1,Cash loans,M,Y,Y,0,315000.0,953460.0,64107.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
95,100113,0,Cash loans,M,Y,N,0,76500.0,135000.0,6696.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
96,100114,0,Cash loans,F,N,Y,0,135000.0,284400.0,22599.0,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,2.0
97,100115,0,Cash loans,F,N,N,0,90000.0,315000.0,14683.5,...,0,0,0,0,0.0,0.0,0.0,0.0,2.0,2.0
98,100116,0,Cash loans,F,N,Y,0,243000.0,900000.0,32017.5,...,0,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
99,100118,0,Cash loans,F,N,Y,0,90000.0,675000.0,26541.0,...,0,0,0,0,NaN,NaN,NaN,NaN,NaN,NaN

#### 還有各種數之不盡的資料操作，重點還是取決於實務中遇到的狀況和你想問的問題，在馬拉松中我們也會陸續提到更多例子